# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get tag name
        id: git-tag
        run: echo ::set-output name=git-version::${GITHUB_REF/refs\/tags\//}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.git-tag.outputs.git-version }}

      - name: Get npm version
        id: npm-tag
        uses: martinbeentjes/npm-get-version-action@master

      - name: Output versions
        run: |
          echo git ${{ steps.git-tag.outputs.git-version }}
          echo npm ${{ steps.npm-tag.outputs.current-version }}

      - name: Versions not matching
        if: steps.git-tag.outputs.git-version != steps.npm-tag.outputs.current-version
        run: |
          echo git and npm versions not equal - refusing to build release
          exit 1

      - name: Version match
        run: |
          echo versions equal - building release ${{ steps.git-tag.outputs.git-version }}

      - name: Install Dependencies
        run: yarn

#      - name: Linter Checks
#        run: yarn lint

      - name: Build Application
        run: yarn build:dirty

      - name: Unit Tests
        run: yarn test:ci

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .conf/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.git-tag.outputs.git-version }}
          labels: ${{ steps.meta.outputs.labels }}

  auth-and-dispatch:
    needs: build-and-push-release
    runs-on: ubuntu-latest

    steps:

      - name: Get tag name
        id: git-tag
        run: echo ::set-output name=git-version::${GITHUB_REF/refs\/tags\//}

      - name: Set env
        run: echo "RELEASE_VERSION=${{ steps.git-tag.outputs.git-version }}" >> $GITHUB_ENV}

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ORG_PORTAL_DISPATCH_APPID }}
          application_private_key: ${{ secrets.ORG_PORTAL_DISPATCH_KEY }}

      - name: Trigger workflow
        id: call_action
        env:
          TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          curl -v \
            --request POST \
            --url https://api.github.com/repos/catenax-ng/product-portal-cd/actions/workflows/portal-registration-int-release-image-update .yml/dispatches \
            --header "authorization: Bearer $TOKEN" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"main", "inputs": { "new-image":"${{ env.RELEASE_VERSION }}" }}' \
            --fail
